# Generated by Django 4.2.16 on 2024-10-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_username', models.CharField(max_length=100)),
                ('player2_username', models.CharField(max_length=100)),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('game_start_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
