# Generated by Django 4.2.16 on 2024-10-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('double', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
