# Generated by Django 4.2.16 on 2024-11-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=100)),
                ('player2', models.CharField(max_length=100)),
                ('player1_alias', models.CharField(max_length=100)),
                ('player2_alias', models.CharField(max_length=100)),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('winner', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('matches', models.ManyToManyField(to='turn.match')),
            ],
        ),
    ]
