# Generated by Django 4.2.16 on 2024-12-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_identifier', models.CharField(max_length=100, unique=True)),
                ('player1', models.CharField(max_length=100)),
                ('player2', models.CharField(max_length=100)),
                ('player1_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('player2_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ball_x', models.FloatField(default=400)),
                ('ball_y', models.FloatField(default=300)),
                ('ball_velocity_x', models.FloatField(default=0)),
                ('ball_velocity_y', models.FloatField(default=0)),
                ('player1_position', models.FloatField(default=0)),
                ('player2_position', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
