# Generated by Django 4.2.16 on 2024-12-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_field',
            field=models.ImageField(blank=True, default='images/profilepng.png', null=True, upload_to='images/'),
        ),
    ]
