# Generated by Django 4.2.16 on 2024-11-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_user_fullname_alter_user_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='no state assigned', max_length=255),
        ),
    ]
