# Generated by Django 4.2.16 on 2024-11-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
