# Generated by Django 4.2.16 on 2024-12-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_friendship_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='status',
        ),
        migrations.AddField(
            model_name='friendship',
            name='user_is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
