# Generated by Django 4.2.16 on 2024-12-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_remove_friendship_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='user_is_logged_in',
            field=models.IntegerField(default=0),
        ),
    ]
